### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'tagged_text_list_train.pkl'

### ISSUE THREAD

**Issue by Thilaga1407** [thestrox/Aspect-Based-Sentiment-Analysis#2]
Hello,

when i run the following code in Aspect Based Sentiment Analysis.ipynb 
![error](https://user-images.githubusercontent.com/44598954/53502031-3ef0f500-3ad3-11e9-85d1-7ac1785bf365.PNG)

i get this error:

Traceback (most recent call last):

  File "<ipython-input-37-10c2f97eaaec>", line 1, in <module>
    tagged_text_list_train=joblib.load('tagged_text_list_train.pkl')

  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\joblib\numpy_pickle.py", line 570, in load
    with open(filename, 'rb') as f:

FileNotFoundError: [Errno 2] No such file or directory: 'tagged_text_list_train.pkl'

Any help please
Thanks

**Comment by thestrox** [comment]
[tagged_text_list_train.pkl](https://github.com/thestrox/Aspect-Based-Sentiment-Analysis/blob/master/tagged_text_list_train.pkl) file is missing. Do you have this file in the same folder as Aspect Based Sentiment Analysis.ipynb?

**Comment by Thilaga1407** [comment]
Yes sir, but instead of running the line i had run the comment line which take time to run

Can I get another help?

How did you store training and testing data in xml format?
Whether do you used your dataset?
How do you represent sentiment and aspect categories in your xml file?

**Comment by thestrox** [comment]
I am closing this issue as you opened another issue for your other questions.
