### ISSUE TITLE
Aspect Based Sentiment 

### ISSUE THREAD

**Issue by Thilaga1407** [thestrox/Aspect-Based-Sentiment-Analysis#3]
Can I get another help?

How did you store training and testing data in xml format?
Whether do you used your dataset?
How do you represent sentiment and aspect categories in your xml file?

**Comment by thestrox** [comment]
I had pointed out that the dataset used for this project were from SemEval in the readme. If you are looking for exact files, go to [this link](http://alt.qcri.org/semeval2016/task5/index.php?id=data-and-tools)
Training Data is the English (Laptops) dataset found in the TRAINING DATA section. 
Test Data is the English (Laptops) dataset found in the TEST DATA: GOLD ANNOTATIONS section. 
Note: I had used the dataset from Subtask 2
