### ISSUE TITLE
ValueError: Classification metrics can't handle a mix of unknown and multilabel-indicator targets

### ISSUE THREAD

**Issue by jyothsnasravas** [thestrox/Aspect-Based-Sentiment-Analysis#4]
hello sir,
while running Aspect Based Sentiment Analysis.ipynb
i am getting this error
![bug1](https://user-images.githubusercontent.com/31766435/53790248-90263c00-3f4c-11e9-8ab9-143ab3e445b4.JPG)
![bug2](https://user-images.githubusercontent.com/31766435/53790250-90bed280-3f4c-11e9-88b5-e971388847c8.JPG)

and 
can you provide exact dataset you are using?

Thank you

**Comment by thestrox** [comment]
I am sorry I will not be able to debug your problem.
For exact dataset: https://github.com/thestrox/Aspect-Based-Sentiment-Analysis/issues/3#issuecomment-472263097

**Comment by jyothsnasravas** [comment]
Thank you for your responce.
